const collectionStore = {
  namespaced: true,
  state: {
    collectionProducts: [
      {
        id: 1,
        title: "Краска Wallquest, Brownsone MS90102",
        available: true,
        sku: 10,
        price: 6000,
        compare_at_price: null,
        rating: 5,
        contract: true,
        exclusive: false,
        featured_image: require("@/assets/products/Product1.png"),
        date: 1374490205,
      },
      {
        id: 2,
        title: "Краска Wallquest, Brownsone MS90102",
        available: false,
        price: 4800,
        compare_at_price: null,
        contract: true,
        exclusive: true,
        rating: 3,
        featured_image: require("@/assets/products/Product2.png"),
        date: 1374490205,
        new: true,
      },
      {
        id: 3,
        title: "Краска Wallquest, Brownsone MS90102",
        available: true,
        sku: 10,
        price: 5290,
        compare_at_price: null,
        contract: false,
        exclusive: false,
        featured_image: require("@/assets/products/Product3.png"),
        date: 1374490316,
        new: true,
      },
      {
        id: 4,
        title: "Краска Wallquest, Brownsone MS90102",
        available: true,
        sku: 10,
        price: 2800,
        compare_at_price: null,
        rating: 4,
        contract: true,
        exclusive: false,
        featured_image: require("@/assets/products/Product4.png"),
        date: 995796732,
        new: false,
      },
      {
        id: 5,
        title: "Краска Wallquest, Brownsone MS90102",
        available: true,
        sku: 10,
        price: 3400,
        compare_at_price: null,
        rating: 2,
        contract: true,
        exclusive: false,
        featured_image: require("@/assets/products/Product5.png"),
        date: 1618061664,
        new: false,
      },
      {
        id: 6,
        title: "Краска Wallquest, Brownsone MS90102",
        available: true,
        sku: 10,
        price: 6000,
        compare_at_price: 8000,
        rating: 3,
        contract: true,
        exclusive: false,
        featured_image: require("@/assets/products/Product6.png"),
        date: 1374490235,
      },
      {
        id: 7,
        title: "Краска Wallquest, Brownsone MS90102",
        available: false,
        price: 4800,
        compare_at_price: 6700,
        contract: true,
        exclusive: true,
        rating: 4,
        featured_image: require("@/assets/products/Product7.png"),
        date: 1374491205,
        new: true,
      },
      {
        id: 8,
        title: "Краска Wallquest, Brownsone MS90102",
        available: true,
        sku: 10,
        price: 5290,
        compare_at_price: null,
        contract: false,
        exclusive: false,
        featured_image: require("@/assets/products/Product8.png"),
        date: 1374490316,
        new: true,
      },
      {
        id: 9,
        title: "Краска Wallquest, Brownsone MS90102",
        available: false,
        sku: 0,
        price: 2800,
        compare_at_price: 3200,
        rating: 4,
        contract: false,
        exclusive: true,
        featured_image: require("@/assets/products/Product9.png"),
        date: 995796732,
        new: true,
      },
      {
        id: 10,
        title: "Краска Wallquest, Brownsone MS90102",
        available: true,
        sku: 10,
        price: 3000,
        compare_at_price: 4000,
        rating: 5,
        contract: true,
        exclusive: false,
        featured_image: require("@/assets/products/Product10.png"),
        date: 1618061644,
        new: false,
      },
      {
        id: 11,
        title: "Краска Wallquest, Brownsone MS90102",
        available: true,
        sku: 10,
        price: 3400,
        compare_at_price: null,
        rating: 2,
        contract: true,
        exclusive: false,
        featured_image: require("@/assets/products/Product5.png"),
        date: 1618061664,
        new: false,
      },
      {
        id: 12,
        title: "Краска Wallquest, Brownsone MS90102",
        available: true,
        sku: 10,
        price: 6000,
        compare_at_price: 8000,
        rating: 3,
        contract: true,
        exclusive: false,
        featured_image: require("@/assets/products/Product6.png"),
        date: 1374490232,
      },
      {
        id: 13,
        title: "Краска Wallquest, Brownsone MS90102",
        available: false,
        price: 4800,
        compare_at_price: 6700,
        contract: true,
        exclusive: true,
        rating: 4,
        featured_image: require("@/assets/products/Product7.png"),
        date: 1374491206,
        new: true,
      },
      {
        id: 14,
        title: "Краска Wallquest, Brownsone MS90102",
        available: true,
        sku: 10,
        price: 5290,
        compare_at_price: null,
        contract: false,
        exclusive: false,
        featured_image: require("@/assets/products/Product8.png"),
        date: 1374490416,
        new: true,
      },
      {
        id: 15,
        title: "Краска Wallquest, Brownsone MS90102",
        available: false,
        sku: 0,
        price: 2800,
        compare_at_price: 3200,
        rating: 4,
        contract: false,
        exclusive: true,
        featured_image: require("@/assets/products/Product9.png"),
        date: 995896732,
        new: true,
      },
      {
        id: 16,
        title: "Краска Wallquest, Brownsone MS90102",
        available: true,
        sku: 10,
        price: 3000,
        compare_at_price: 4000,
        rating: 5,
        contract: true,
        exclusive: false,
        featured_image: require("@/assets/products/Product10.png"),
        date: 1618461644,
        new: false,
      },
    ],
  },
  getters: {
    collectionProducts: ({ collectionProducts }) => collectionProducts,
    totalProducts: ({ collectionProducts }) => collectionProducts.length,
  },
};

export default collectionStore;
